export default {
  FETCH_COLORS_REQUEST: 'FETCH_COLORS_REQUEST',
  FETCH_COLORS_SUCCESS: 'FETCH_COLORS_SUCCESS',
  FETCH_COLORS_FAILURE: 'FETCH_COLORS_FAILURE',
  CHANGE_BACKGROUND_COLOR: 'CHANGE_BACKGROUND_COLOR',
};

